server {
    listen       80;
    server_name  gorani.me www.gorani.me 192.168.1.234;

    root   C:/Users/ksj/nginx-1.29.2/html/gorani.me;
    index  index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* \.(js|css|png|jpg|jpeg|gif|svg|ico|webp|map|txt)$ {
        expires 7d;
        add_header Cache-Control "public, max-age=604800";
    }
}
